#!/bin/ksh

# If no arguments are provided, use fzf to select a file
if [ $# -eq 0 ]; then
    set -- "$(fzf)"
fi

# If still no file is selected, exit
[ -z "$1" ] && exit 1

# Determine the MIME type and open the file with the appropriate application
case "$(file -b --mime-type -- "$1")" in
    image/*) nsxiv "$1" ;;
    video/*|audio/*) mpv "$1" ;;
    application/pdf) mupdf "$1" ;;
    text/*) vim "$1" ;;
    *) xdg-open "$1" ;;
esac
